title: PFSGE # title
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
  Pulsed-field Spiral gel electrophoresis is an extraction method to separate the large DNA molecule  
  <br><br>
  <a href="https://www.PFSGE.io">Click here for Demo </a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-145472962-1 # your Google Analytics tracking ID here
